
# Generated by Django 4.0.6 on 2022-09-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200, unique=True)),
                ('number_phone', models.CharField(max_length=20, unique=True)),
                ('contact', models.CharField(max_length=50, unique=True)),
                ('adress', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('image_logo', models.ImageField(blank=True, upload_to='static/logo/')),
            ],
        ),
    ]
