# Generated by Django 4.0.6 on 2022-09-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayphat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=200, unique=True)),
                ('image_slide', models.ImageField(blank=True, upload_to='static/mayphat/slide_hinh')),
            ],
        ),
    ]
