# Generated by Django 4.0.6 on 2022-09-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayphat', '0004_slide_status_alter_slide_image_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image_slide',
            field=models.ImageField(blank=True, upload_to='static/mayphat/slide_hinh/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='status',
            field=models.CharField(choices=[('Slide', 'Slide'), ('Banner', 'Banner')], default='Slide', max_length=15),
        ),
    ]
