# Generated by Django 4.0.6 on 2022-09-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayphat', '0005_alter_slide_image_slide_alter_slide_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nation',
            field=models.IntegerField(default=10.53),
            preserve_default=False,
        ),
    ]
