# Generated by Django 4.0.6 on 2022-10-17 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mayphat', '0007_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posttest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('city', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('insurance', 'insurance'), ('repair', 'repair'), ('service', 'service'), ('transport', 'transport')], default='insurance', max_length=15),
        ),
        migrations.CreateModel(
            name='Imageslide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(blank=True, upload_to='static/mayphat/slide_sp/')),
                ('category_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mayphat.category')),
            ],
        ),
    ]
