# Generated by Django 4.0.6 on 2022-10-17 02:46

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mayphat', '0008_posttest_post_status_imageslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('product_id', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='static/mayphat/image_product/')),
                ('slide_sp', models.ImageField(blank=True, upload_to='static/mayphat/slide_sp/')),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('amount', models.IntegerField(default=0)),
                ('detail', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
