# Generated by Django 4.0.6 on 2022-10-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayphat', '0009_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slide_sp',
        ),
        migrations.AddField(
            model_name='category',
            name='product_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default=123, max_length=180),
            preserve_default=False,
        ),
    ]
