# Generated by Django 4.0.6 on 2022-10-17 03:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayphat', '0010_remove_product_slide_sp_category_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
