# Generated by Django 4.0.6 on 2022-10-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayphat', '0011_category_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_name', models.CharField(max_length=50)),
            ],
        ),
    ]
