# Generated by Django 4.1.2 on 2022-11-10 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mayphat", "0015_delete_cart_delete_posttest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("text", models.CharField(max_length=500)),
                ("rating", models.IntegerField(default=0)),
                (
                    "id_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mayphat.category",
                    ),
                ),
            ],
        ),
    ]
