# Generated by Django 4.1.2 on 2022-11-16 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mayphat", "0016_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_code", models.CharField(max_length=20)),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=200)),
                ("number_phone", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=100)),
                ("payment_methosd", models.CharField(max_length=400)),
                ("payment_data", models.CharField(max_length=400)),
                ("tax_data", models.CharField(max_length=50)),
                ("company_name", models.CharField(max_length=100)),
                ("company_adress", models.CharField(max_length=100)),
                ("items", models.TextField()),
                ("fulfilled", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Order_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "price_update",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("amount", models.IntegerField(default=0)),
                (
                    "id_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mayphat.category",
                    ),
                ),
                (
                    "id_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mayphat.order"
                    ),
                ),
            ],
        ),
    ]
