# Generated by Django 4.1.2 on 2022-11-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mayphat", "0017_order_order_detail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="items", new_name="comment",
        ),
    ]
