# Generated by Django 4.1.2 on 2022-11-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mayphat", "0018_rename_items_order_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
