# Generated by Django 4.1.2 on 2022-11-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mayphat", "0021_alter_order_full_name_alter_order_payment_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_code",
            field=models.IntegerField(default=100000),
        ),
    ]
