# Generated by Django 4.0.6 on 2022-11-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayphat', '0022_alter_order_payment_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
