# Generated by Django 4.0.6 on 2022-11-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayphat', '0023_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('insurance', 'insurance'), ('repair', 'repair'), ('transport', 'transport')], default='insurance', max_length=15),
        ),
    ]
