# Generated by Django 4.0.6 on 2022-11-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayphat', '0024_remove_category_product_id_alter_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='company_adress',
        ),
        migrations.RemoveField(
            model_name='order',
            name='company_name',
        ),
    ]
