# Generated by Django 4.1.2 on 2022-11-28 06:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mayphat", "0025_remove_order_company_adress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="user_update",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
