# Generated by Django 4.1.2 on 2022-11-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mayphat", "0026_order_date_order_user_update"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="date", new_name="order_date",
        ),
    ]
