# Generated by Django 4.1.2 on 2022-11-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mayphat", "0027_rename_date_order_order_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="order_date",),
    ]
