# Generated by Django 4.1.2 on 2022-11-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mayphat", "0031_remove_order_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="update_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
