# Generated by Django 4.1.2 on 2022-11-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mayphat", "0032_order_update_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[("OK", "OK"), ("Delivery", "Delivery"), ("Cancel", "Cancel")],
                default="OK",
                max_length=15,
            ),
        ),
    ]
