# Generated by Django 4.1.2 on 2022-11-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mayphat", "0033_order_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("OK", "OK"),
                    ("Delivery", "Delivery"),
                    ("Cancel", "Cancel"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_data",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="tax_data",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
