# Generated by Django 4.1.2 on 2022-11-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mayphat", "0034_alter_order_comment_alter_order_order_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="fulfilled",
            field=models.BooleanField(verbose_name="Đã Thanh Toán"),
        ),
    ]
