# Generated by Django 4.1.2 on 2022-11-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mayphat", "0035_alter_order_fulfilled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="fulfilled",
            field=models.BooleanField(verbose_name="Payment already"),
        ),
    ]
