# Generated by Django 4.1.2 on 2022-11-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mayphat", "0036_alter_order_fulfilled"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="company_data",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
