# Generated by Django 4.1.2 on 2022-11-29 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mayphat", "0037_order_company_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderSummary",
            fields=[],
            options={
                "verbose_name": "Order Summary",
                "verbose_name_plural": "Orders Summary",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("mayphat.order",),
        ),
    ]
