# Generated by Django 4.1.2 on 2022-11-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mayphat", "0038_ordersummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_detail",
            name="create_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
