# Generated by Django 4.1.2 on 2022-11-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mayphat", "0039_order_detail_create_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_detail",
            name="ship_cost",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
