# Generated by Django 4.0.6 on 2022-12-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayphat', '0040_order_detail_ship_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company_adress',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
