# Generated by Django 4.1.2 on 2022-12-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mayphat", "0041_order_company_adress_order_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order", name="payment_code", field=models.IntegerField(),
        ),
    ]
