# Generated by Django 4.0.6 on 2022-12-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayphat', '0042_alter_order_payment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='company_adress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('rental', 'rental'), ('repair', 'repair'), ('transport', 'transport')], default='rental', max_length=15),
        ),
    ]
